import { createFileRoute, notFound, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle2, Upload, ArrowLeft, ArrowRight, PartyPopper } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { getService, generateRef, DEMO_PROFILE, STATES, DISTRICTS_UP } from "@/lib/data";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route = createFileRoute("/apply/$serviceId")({
  loader: ({ params }) => {
    const service = getService(params.serviceId);
    if (!service) throw notFound();
    return service;
  },
  head: ({ loaderData }) => ({
    meta: [
      { title: `Application Assistant — ${loaderData?.name ?? "Service"} — SevaSetu` },
      {
        name: "description",
        content: "Guided step-by-step application for public services with document checklists.",
      },
      { property: "og:title", content: "Application Assistant — SevaSetu" },
      { property: "og:description", content: "Guided application with document support." },
      { property: "og:type", content: "website" },
    ],
  }),
  component: ApplyPage,
});

const STEP_TITLES = ["Personal Details", "Eligibility", "Documents", "Review", "Submit"];

function ApplyPage() {
  const service = Route.useLoaderData();
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [submitting, setSubmitting] = useState(false);
  const [submittedRef, setSubmittedRef] = useState<string | null>(null);
  const [uploaded, setUploaded] = useState<Record<string, boolean>>({});
  const [form, setForm] = useState({
    name: DEMO_PROFILE.name,
    state: DEMO_PROFILE.state,
    district: DEMO_PROFILE.district,
    ageGroup: DEMO_PROFILE.ageGroup,
    employment: DEMO_PROFILE.occupation,
    income: "Below ₹1 lakh",
  });

  const set = (k: keyof typeof form) => (v: string) => setForm((f) => ({ ...f, [k]: v }));

  async function submit() {
    setSubmitting(true);
    const ref = generateRef("SV");
    const { error } = await supabase.from("applications").insert({
      ref,
      citizen_id: DEMO_PROFILE.id,
      citizen_name: form.name,
      service_id: service.id,
      service_name: service.name,
      category: service.category,
      district: form.district,
      state: form.state,
      status: "Submitted",
      details: {
        age_group: form.ageGroup,
        employment: form.employment,
        income: form.income,
        documents_confirmed: Object.keys(uploaded).filter((k) => uploaded[k]),
      },
    });
    setSubmitting(false);
    if (error) {
      toast.error("Could not submit the application. Please try again.");
      return;
    }
    setSubmittedRef(ref);
    toast.success(`Application ${ref} submitted`);
  }

  if (submittedRef) {
    return (
      <div className="mx-auto max-w-xl px-4 py-16 text-center">
        <PartyPopper className="mx-auto h-12 w-12 text-success" aria-hidden />
        <h1 className="mt-4 text-3xl font-bold">Application Submitted</h1>
        <p className="mt-3 text-muted-foreground">
          Your application for <span className="font-medium text-foreground">{service.name}</span>{" "}
          has been received.
        </p>
        <Card className="mt-6 shadow-none">
          <CardContent className="space-y-2 p-6">
            <p className="text-sm text-muted-foreground">Application ID (demo)</p>
            <p className="text-2xl font-bold tracking-wide text-primary">{submittedRef}</p>
            <p className="text-sm">
              Status: <span className="font-medium">Submitted</span>
            </p>
          </CardContent>
        </Card>
        <div className="mt-6 flex justify-center gap-3">
          <Button onClick={() => navigate({ to: "/track", search: { ref: submittedRef } })}>
            Track Application
          </Button>
          <Button variant="outline" onClick={() => navigate({ to: "/dashboard" })}>
            Back to Dashboard
          </Button>
        </div>
        <p className="mt-6 text-xs text-muted-foreground">
          Demo data — this application ID is generated by the prototype.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      <h1 className="text-3xl font-bold">Application Assistant</h1>
      <p className="mt-2 text-muted-foreground">
        {service.name} · guided step-by-step application
      </p>

      <div className="mt-6">
        <div className="flex items-center justify-between text-sm">
          <span className="font-medium">
            Step {step + 1} of {STEP_TITLES.length}: {STEP_TITLES[step]}
          </span>
        </div>
        <Progress value={((step + 1) / STEP_TITLES.length) * 100} className="mt-2" />
      </div>

      <Card className="mt-6 shadow-none">
        <CardContent className="space-y-5 p-6">
          {step === 0 && (
            <>
              <div className="space-y-2">
                <Label htmlFor="name">Full name</Label>
                <Input
                  id="name"
                  value={form.name}
                  onChange={(e) => set("name")(e.target.value)}
                />
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-2">
                  <Label>State</Label>
                  <Select value={form.state} onValueChange={set("state")}>
                    <SelectTrigger aria-label="State">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {STATES.map((s) => (
                        <SelectItem key={s} value={s}>
                          {s}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>District</Label>
                  <Select value={form.district} onValueChange={set("district")}>
                    <SelectTrigger aria-label="District">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {DISTRICTS_UP.map((d) => (
                        <SelectItem key={d} value={d}>
                          {d}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <p className="text-xs text-muted-foreground">
                Prototype: pre-filled with demo profile data. Do not enter real sensitive
                identifiers.
              </p>
            </>
          )}

          {step === 1 && (
            <>
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="space-y-2">
                  <Label>Age group</Label>
                  <Select value={form.ageGroup} onValueChange={set("ageGroup")}>
                    <SelectTrigger aria-label="Age group">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {["Under 18", "18–30", "31–59", "60+"].map((o) => (
                        <SelectItem key={o} value={o}>
                          {o}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Employment</Label>
                  <Select value={form.employment} onValueChange={set("employment")}>
                    <SelectTrigger aria-label="Employment status">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {["Student", "Employed", "Self-employed", "Unemployed", "Other"].map((o) => (
                        <SelectItem key={o} value={o}>
                          {o}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Household income</Label>
                  <Select value={form.income} onValueChange={set("income")}>
                    <SelectTrigger aria-label="Income range">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {["Below ₹1 lakh", "₹1–3 lakh", "₹3–5 lakh", "Above ₹5 lakh"].map((o) => (
                        <SelectItem key={o} value={o}>
                          {o}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <p className="rounded-md border bg-muted px-4 py-3 text-sm text-muted-foreground">
                Based on this service's criteria: {service.eligibility}
              </p>
            </>
          )}

          {step === 2 && (
            <>
              <h3 className="text-sm font-semibold">Required Documents</h3>
              <ul className="space-y-3">
                {service.documents.map((doc, i) => {
                  const required = i < 3;
                  const done = uploaded[doc];
                  return (
                    <li
                      key={doc}
                      className="flex items-center justify-between rounded-md border px-4 py-3"
                    >
                      <span className="flex items-center gap-2 text-sm">
                        {done ? (
                          <CheckCircle2 className="h-4 w-4 text-success" aria-hidden />
                        ) : (
                          <span
                            className="flex h-4 w-4 items-center justify-center rounded-full border text-[10px] text-muted-foreground"
                            aria-hidden
                          >
                            {required ? "✓" : "○"}
                          </span>
                        )}
                        {doc}
                        {!required && (
                          <span className="text-xs text-muted-foreground">(optional)</span>
                        )}
                      </span>
                      <Button
                        variant={done ? "secondary" : "outline"}
                        size="sm"
                        onClick={() => {
                          setUploaded((u) => ({ ...u, [doc]: !done }));
                          if (!done) toast.success(`${doc} attached (demo)`);
                        }}
                      >
                        <Upload className="mr-1.5 h-3.5 w-3.5" aria-hidden />
                        {done ? "Attached" : "Attach (demo)"}
                      </Button>
                    </li>
                  );
                })}
              </ul>
              <p className="text-xs text-muted-foreground">
                Demo upload controls — no files are actually uploaded or stored.
              </p>
            </>
          )}

          {step === 3 && (
            <>
              <h3 className="text-base font-semibold">Review Before Submission</h3>
              <dl className="grid gap-x-6 gap-y-3 rounded-md border p-4 text-sm sm:grid-cols-2">
                <div>
                  <dt className="text-muted-foreground">Service</dt>
                  <dd className="font-medium">{service.name}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">Applicant</dt>
                  <dd className="font-medium">{form.name}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">Location</dt>
                  <dd className="font-medium">
                    {form.district}, {form.state}
                  </dd>
                </div>
                <div>
                  <dt className="text-muted-foreground">Profile</dt>
                  <dd className="font-medium">
                    {form.ageGroup} · {form.employment} · {form.income}
                  </dd>
                </div>
                <div className="sm:col-span-2">
                  <dt className="text-muted-foreground">Documents attached</dt>
                  <dd className="font-medium">
                    {Object.keys(uploaded).filter((k) => uploaded[k]).length} of{" "}
                    {service.documents.length}
                  </dd>
                </div>
              </dl>
            </>
          )}

          {step === 4 && (
            <div className="py-4 text-center">
              <h3 className="text-lg font-semibold">Ready to submit</h3>
              <p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">
                By submitting, your demo application will be sent for document verification and
                will appear in application tracking and on the department dashboard.
              </p>
            </div>
          )}

          <div className="flex justify-between border-t pt-5">
            <Button variant="outline" disabled={step === 0} onClick={() => setStep((s) => s - 1)}>
              <ArrowLeft className="mr-2 h-4 w-4" aria-hidden /> Back
            </Button>
            {step < STEP_TITLES.length - 1 ? (
              <Button onClick={() => setStep((s) => s + 1)}>
                Continue <ArrowRight className="ml-2 h-4 w-4" aria-hidden />
              </Button>
            ) : (
              <Button onClick={submit} disabled={submitting}>
                {submitting ? "Submitting…" : "Submit Application"}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
